# Generated by Django 5.0.6 on 2024-07-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('species', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('submitter', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('vaccination', models.ManyToManyField(blank=True, to='adoptions.vaccine')),
            ],
        ),
    ]
